config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :products do
  	member do 
	  	get 'back'
	  	get 'report'
      get 'like'
	  end
    collection do
      get 'favorite'
      get 'popular'
      get 'recommended'
    end
  end 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks",registrations: 'registrations' }
  root 'home#index'

  get 'my_projects' =>'products#my_products'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :back_products,:dependent => :destroy
	has_many :report_products,:dependent => :destroy

	acts_as_taggable

	ratyrate_rateable "speed", "engine", "price"
	acts_as_likeable

	has_attached_file :image, styles: { small: "64x64>", large: "250x250>" }
	has_attached_file :video
	
	validates_attachment :image, presence: true, :content_type => { :content_type => /\Aimage/ }, :size => { :in => 0..5.megabytes }
  validates_attachment :video, presence: true, :content_type => { :content_type => /\Avideo/ }, :size => { :in => 0..25.megabytes }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, only: [:show, :edit, :update, :destroy,:back,:report,:like]
  before_action :authenticate_user!, except: [:index]

	# GET /products
  # GET /products.json
  def index
    if params["category_id"].nil?
      @products = Product.all.where(:active=>true)
    else
      @products = Product.where(:category_id=>params["category_id"],:active=>true)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
  	@product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product,  notice: "Product created Successfully" }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product updated Successfully" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def my_products
    if params["category_id"].nil?
      @products = Product.where(:user_id=>current_user.id)
    else
      @products = Product.where(:category_id=>params["category_id"],:user_id=>current_user.id)
    end
  end

  def back
    BackProduct.create(:product_id=>@product.id,:user_id=>current_user.id)
    backers_total = @product.backers_total + 1
    @product.update_columns(:backers_total=>backers_total)
    respond_to do |format|
      format.html { redirect_to @product }
    end
  end

  def report
    ReportProduct.create(:product_id=>@product.id,:user_id=>current_user.id)
    respond_to do |format|
      format.html { redirect_to @product }
    end
  end

  def like
    current_user.like!(@product)
    respond_to do |format|
      format.html { redirect_to @product }
    end
  end

  def recommended
    if params["category_id"].nil?
      @products = Product.all.where(:active=>true)
    else
      @products = Product.where(:category_id=>params["category_id"],:active=>true)
    end
  end

  def popular
    if params["category_id"].nil?
      @products = Product.all.where('backers_total >?',0).sort_by(&:backers_total)
    else
      @products = Product.where('category_id =? and backers_total >?',params["category_id"],0).sort_by(&:backers_total)
    end
  end

  def favorite
    liked_product_ids = Like.where(:liker_id=>1).pluck(:id)
    if params["category_id"].nil?
      @products = Product.where(:id=>liked_product_ids)
    else
      @products = Product.where(:id=>liked_product_ids,:category_id=>params["category_id"])
    end
  end

  private

  	# Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :project, :funding_goal, :description, :category_id, :facebook_url, :website,:risks,:user_id,:location,:future_plans,:short_description,:raised_amount,:backers_total,:tag_list,:image,:video)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="projectTab">
  <div class="container">
    <div class="row">
      <div class="col-md-12"> 
        <!-- Nav tabs -->
        <div class="card marginTop20">
            

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="home">
              <h1 class="text-center regularfont">Let’s get started.</h1>
              <h3 class="text-center lineHeight24">Make a great first impression with your project’s title and image, and set your funding goal, campaign duration, and project category.</h3>

              <div class="contentproject">
                <div class="row">
                  <div class="col-md-9">
                    <%= form_for(@product, multipart: true) do |f| %>
                      
                      <div class="bs-calltoaction bs-calltoaction-info">
                          <div class="form-group">
                            <label for="email">Project Image:</label>
                            <%= f.file_field :image, class: "form-control",:required=>true %>
                          </div>
                      </div>
                      <div class="bs-calltoaction bs-calltoaction-info">
                          <div class="form-group">
                            <label for="title">Project Title:</label>
                            <%= f.text_field :title,:class=>"form-control",:placeholder=>"Enter you title",:required=>true %>
                          </div>
                      </div>
                      
                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                            <label for="email">Category:</label>
                            <!--<input type="text" class="form-control" id="email"> -->
                            <%= f.select :category_id,Category.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, {:class=>"form-control",:required=>true}  %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <label for="location">Project Location:</label>
                          <%= f.text_field :location,:class=>"form-control",:required=>true %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <label for="email">Funding goal:</label>
                          <%= f.text_field :funding_goal,:class=>"form-control",:placeholder=>"$0",:required=>true %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <label for="email">Website:</label>
                          <%= f.text_field :website,:class=>"form-control",:required=>true %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <label for="email">Short Description:</label>
                          <%= f.text_field :short_description,:class=>"form-control",:required=>true %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <label for="description">Project description:</label>
                          <%= f.text_area :description,:class=>"form-control",:rows=>6,:placeholder=>"Use your project description to share more about what you’re raising funds to do and how you plan to pull it off. It’s up to you to make the case for your project.",:required=>true %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <%= f.label :tag_list, "Tags (separated by commas)" %>
                          <%= f.text_field :tag_list,:class=>"form-control" %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <label for="description">Risks and challenges:</label>
                          <%= f.text_area :risks,:class=>"form-control",:rows=>6,:placeholder=>"What are the risks and challenges that come with completing your project, and how are you qualified to overcome them?",:required=>true %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                        <div class="form-group">
                          <label for="description">Future Plans:</label>
                          <%= f.text_area :future_plans,:class=>"form-control",:rows=>4,:placeholder=>"",:required=>true %>
                        </div>
                      </div>

                      <div class="bs-calltoaction bs-calltoaction-info">
                          <div class="form-group">
                            <label for="email">Project Video:</label>
                            <%= f.file_field :video, class: "form-control",:required=>true%>
                          </div>
                      </div>

                      <div class="text-center">
                        <%= f.hidden_field :user_id, :value=>current_user.id %>
                        <%= f.button :submit, value: "Save",:class=>"btn btn-primary btn-lg" %> 
                      </div>

                    <% end %>

                  </div>
                  <div class="col-md-3 marginTop10">
                    <div class="panel panel-default">
                      <div class="panel-body">
                        <div class="pull-left"><span class="fa fa-lightbulb-o fa-2x"></span>
                        &nbsp;</div>
                        <div class="pull-left">
                        <span>How to</span>
                        <span class="displayBlock">Make an awesome project</span>
                        </div>
                      </div>
                    </div> <!-- panel -->

                    <h5>Need advice ?</h5>
                    <p>Visit Campus to read discussions about <a href="">preparing for a project</a> and more.</p>

                    
                  </div>
                </div>
              </div> <!-- contentproject -->
            </div>
          </div> <!-- tab content -->
        </div>
      </div>
    </div>
  </div>  
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/favorite.html.erb
<div class="jumbotron">
  <div class="container"> 
    <%= form_tag(favorite_products_path, :method => :get) do %>
      <%= select_tag 'category_id', options_for_select(Category.all.map{ |category| [category.name,category.id]}), {:prompt => "All Categories",:id=>"soflow",onchange: "this.form.submit();"} %>
    <% end %>
    <h4>Bright new ideas, handpicked by us.</h4>
    <h4 class="marginTop20 regularfont">Refine search</h4>
  </div>
</div>

                  
<!-- Recommended-->
<div class="">
  <div class="container">
    <h3 class="regularfont">Explore <%= @products.count %> live projects</h3>

      <div class="row marginTop20"> 
        <% @products.each do |product| %>
          <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
              <% if product.image.content_type.nil? %>
                <%= link_to product_path(product) do %>
                  <%= image_tag "pic1.jpg" %>
                <% end %>
              <% else %>
                <%= link_to product_path(product) do %>
                  <%= image_tag product.image.url(:large),:class=>"products_image" %>
                <% end %>
              <% end %>
              <div class="caption">
                <h5 class="regularfont"><%= link_to product.short_description.slice(0,55),product_path(product) %></h5>
                <p>by <%= product.user.name %></p>

                <p class="marginTop10"><%= product.description.slice(0,130) %></p>

                <p class="marginTop20">
                  <span><%= fa_icon "map-marker" %>  <%= product.location %>  </span>
                </p>
                <div class="progress customPrograss">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    <span class="sr-only">0% Complete (success)</span>
                  </div>
                </div>
              </div>

              <ul class="packages">
                <li>
                  <strong class="displayBlock">0%</strong>
                  <span>funded</span>
                </li>
                <li>
                  <strong class="displayBlock">$<%= product.funding_goal %></strong>
                  <span>Goal</span>
                </li>
                <li>
                  <strong class="displayBlock">60</strong>
                  <span>days to go</span>
                </li>
              </ul>
            </div> <!-- thumbnail -->
          </div> <!-- col-md-3 -->
        <% end %>
      </div> <!-- row --> 

  </div> <!-- container -->
</div>
<!-- Recommended-->

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th>Funding goal</th>
      <th>Description</th>
      <th>Categry</th>
      <th>Facebook url</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.project %></td>
        <td><%= product.funding_goal %></td>
        <td><%= product.description %></td>
        <td><%= product.categry %></td>
        <td><%= product.facebook_url %></td>
        <td><%= product.website %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/my_products.html.erb
<div class="jumbotron">
  <div class="container"> 
    <%= form_tag(my_projects_path, :method => :get) do %>
      <%= select_tag 'category_id', options_for_select(Category.all.map{ |category| [category.name,category.id]}), {:prompt => "All Categories",:id=>"soflow",onchange: "this.form.submit();"} %>
    <% end %>
    <h4>Bright new ideas, handpicked by us.</h4>
    <h4 class="marginTop20 regularfont">Refine search</h4>
  </div>
</div>

                  
<!-- Recommended-->
<div class="">
  <div class="container">
    <h3 class="regularfont">Explore <%= @products.count %> live projects</h3>

      <div class="row marginTop20"> 
        <% @products.each do |product| %>
          <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
              <% if product.image.content_type.nil? %>
                <%= link_to product_path(product) do %>
                  <%= image_tag "pic1.jpg" %>
                <% end %>
              <% else %>
                <%= link_to product_path(product) do %>
                  <%= image_tag product.image.url(:large),:class=>"products_image" %>
                <% end %>
              <% end %>
              <div class="caption">
                <h5 class="regularfont"><%= link_to product.short_description.slice(0,55),product_path(product) %></h5>
                <p>by <%= product.user.name %></p>

                <p class="marginTop10"><%= product.description.slice(0,130) %></p>

                <p class="marginTop20">
                  <span><%= fa_icon "map-marker" %>  <%= product.location %>  </span>
                </p>
                <div class="progress customPrograss">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    <span class="sr-only">0% Complete (success)</span>
                  </div>
                </div>
              </div>

              <ul class="packages">
                <li>
                  <strong class="displayBlock">0%</strong>
                  <span>funded</span>
                </li>
                <li>
                  <strong class="displayBlock">$<%= product.funding_goal %></strong>
                  <span>Goal</span>
                </li>
                <li>
                  <strong class="displayBlock">60</strong>
                  <span>days to go</span>
                </li>
              </ul>
            </div> <!-- thumbnail -->
          </div> <!-- col-md-3 -->
        <% end %>
      </div> <!-- row --> 

  </div> <!-- container -->
</div>
<!-- Recommended-->

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/popular.html.erb
<div class="jumbotron">
  <div class="container"> 
    <%= form_tag(popular_products_path, :method => :get) do %>
      <%= select_tag 'category_id', options_for_select(Category.all.map{ |category| [category.name,category.id]}), {:prompt => "All Categories",:id=>"soflow",onchange: "this.form.submit();"} %>
    <% end %>
    <h4>Bright new ideas, handpicked by us.</h4>
    <h4 class="marginTop20 regularfont">Refine search</h4>
  </div>
</div>

                  
<!-- Recommended-->
<div class="">
  <div class="container">
    <h3 class="regularfont">Explore <%= @products.count %> live projects</h3>

      <div class="row marginTop20"> 
        <% @products.each do |product| %>
          <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
              <% if product.image.content_type.nil? %>
                <%= link_to product_path(product) do %>
                  <%= image_tag "pic1.jpg" %>
                <% end %>
              <% else %>
                <%= link_to product_path(product) do %>
                  <%= image_tag product.image.url(:large),:class=>"products_image" %>
                <% end %>
              <% end %>
              <div class="caption">
                <h5 class="regularfont"><%= link_to product.short_description.slice(0,55),product_path(product) %></h5>
                <p>by <%= product.user.name %></p>

                <p class="marginTop10"><%= product.description.slice(0,130) %></p>

                <p class="marginTop20">
                  <span><%= fa_icon "map-marker" %>  <%= product.location %>  </span>
                </p>
                <div class="progress customPrograss">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    <span class="sr-only">0% Complete (success)</span>
                  </div>
                </div>
              </div>

              <ul class="packages">
                <li>
                  <strong class="displayBlock">0%</strong>
                  <span>funded</span>
                </li>
                <li>
                  <strong class="displayBlock">$<%= product.funding_goal %></strong>
                  <span>Goal</span>
                </li>
                <li>
                  <strong class="displayBlock">60</strong>
                  <span>days to go</span>
                </li>
              </ul>
            </div> <!-- thumbnail -->
          </div> <!-- col-md-3 -->
        <% end %>
      </div> <!-- row --> 

  </div> <!-- container -->
</div>
<!-- Recommended-->

app/views/products/recommended.html.erb
<div class="jumbotron">
  <div class="container"> 
    <%= form_tag(recommended_products_path, :method => :get) do %>
      <%= select_tag 'category_id', options_for_select(Category.all.map{ |category| [category.name,category.id]}), {:prompt => "All Categories",:id=>"soflow",onchange: "this.form.submit();"} %>
    <% end %>
    <h4>Bright new ideas, handpicked by us.</h4>
    <h4 class="marginTop20 regularfont">Refine search</h4>
  </div>
</div>

                  
<!-- Recommended-->
<div class="">
  <div class="container">
    <h3 class="regularfont">Explore <%= @products.count %> live projects</h3>

      <div class="row marginTop20"> 
        <% @products.each do |product| %>
          <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
              <% if product.image.content_type.nil? %>
                <%= link_to product_path(product) do %>
                  <%= image_tag "pic1.jpg" %>
                <% end %>
              <% else %>
                <%= link_to product_path(product) do %>
                  <%= image_tag product.image.url(:large),:class=>"products_image" %>
                <% end %>
              <% end %>
              
              <div class="caption">
                <h5 class="regularfont"><%= link_to product.short_description.slice(0,55),product_path(product) %></h5>
                <p>by <%= product.user.name %></p>

                <p class="marginTop10"><%= product.description.slice(0,130) %></p>

                <p class="marginTop20">
                  <span><%= fa_icon "map-marker" %>  <%= product.location %>  </span>
                </p>
                <div class="progress customPrograss">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                    <span class="sr-only">0% Complete (success)</span>
                  </div>
                </div>
              </div>

              <ul class="packages">
                <li>
                  <strong class="displayBlock">0%</strong>
                  <span>funded</span>
                </li>
                <li>
                  <strong class="displayBlock">$<%= product.funding_goal %></strong>
                  <span>Goal</span>
                </li>
                <li>
                  <strong class="displayBlock">60</strong>
                  <span>days to go</span>
                </li>
              </ul>
            </div> <!-- thumbnail -->
          </div> <!-- col-md-3 -->
        <% end %>
      </div> <!-- row --> 

  </div> <!-- container -->
</div>
<!-- Recommended-->

app/views/products/show.html.erb
<%= javascript_include_tag 'jquery.raty.js','ratyrate.js'%>
<!-- blog -->
<div class="container">
        
  <br />
  <h1 >
    <%= @product.user.name %>
  </h1>

  <h4 class="col-md-8 marginLeft-15"><%= @product.short_description %></h4>

  <div class="row">
    <div class="col-md-8">
  
      <!--  <img src="http://placehold.it/900x300" class="img-responsive"> -->
    
      <div class="vid">
        
        <% if @product.video.content_type.nil? %>
          <video width="100%" controls="">
            <source src="https://ksr-video.imgix.net/projects/2760435/video-738279-h264_high.mp4" type="video/mp4">
          </video>
        <% else %>
          <%= video_tag @product.video.url(), :controls => true,:width=>"100%"  %> 
        <% end %>
          
      </div> <!-- vid -->

      <hr>
      <p class="lead"><%= @product.description %></p>
      <p><b>Future Plans: </b> <%= @product.future_plans %></p>
      <p><b>Risks and Challenges: </b><%= @product.risks %></p>
      <hr>

      <div class="pull-left">
        <% if @product.user.image.content_type.nil? %>   
          <%= image_tag "julia.jpg" ,:class=>"img-circle" %>
        <% else %>
          <%= image_tag @product.user.image.url(:small) ,:class=>"img-circle" %>
        <% end %>
        <p>By <%= @product.user.name %> </p>
        <p><%= time_ago_in_words(@product.created_at) + " ago" %></p>
        <p><button class="btn btn-default">Follow</button></p>
      </div>
      <div class="pull-right">
        <p>
          <i class="fa fa-calendar"></i> Posted on <%= @product.created_at.strftime("%d %b. %Y") %>
        </p>
        <p>
          <i class="fa fa-tags"></i> Category: <a href=""><span class="badge badge-info"><%= @product.category.name %></span></a> 
        </p>
        <p>
          <i class="fa fa-tags"></i> Tags: 
          <a href="">
            <% @product.tag_list.each do |tag| %>
              <span class="badge badge-info">
                <%= tag %>
              </span>
            <% end %>
          </a> 
        </p>
      </div>
      <div class="clearfix"></div>
      <hr>
    </div> <!-- col-md-8 -->

    <div class="col-md-4">                  
      <div class="borderTopgreen"></div>
      <h2>$<%= @product.raised_amount.nil? ? 0 : @product.raised_amount %></h2>
      <p>rasied of $<%= @product.funding_goal %> goal</p>

      <div style="margin-top:20px;"></div>
      Rating : <%= rating_for @product, 'engine' %>

      <h2><%= @product.backers_total %></h2>
      <p>backers</p>

      <h2>60</h2>
      <p>days to go</p>

      <% backed = BackProduct.where(:user_id=>current_user.id,:product_id=>@product.id) %>

      <%= link_to "Back this Project" ,back_product_path(@product),:class=>"btn btn-success btn-lg product_back_button" %>
      <p class="marginTop20">
        <%= link_to like_product_path(@product),:class=>"btn btn-default" do %>
          <%= fa_icon "heart" %> Favourite <b><%= @product.likers(User).count %></b>
        <% end %>&nbsp;&nbsp;
        <button class="btn btn-default"><i class="fa fa-share"></i> Share</button>
        <%= link_to report_product_path(@product),:class=>"btn btn-default" do %>
        <%= fa_icon "flag" %> Report <b><%= ReportProduct.where(:product_id=>@product.id).count %></b>
      <% end %>
      </p>
      <% if @product.user == current_user %>
        <p>
          <%= link_to edit_product_path(@product),:class=>"btn btn-info btn-lg product_edit_button" do %>
            <%= fa_icon "edit" %> Edit
          <% end %>
        </p>
      <% end %>
      <% if @product.user == current_user %>
        <p>
          <%= link_to @product,  method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-lg product_destroy_button" do %>
            <%= fa_icon "trash" %> Delete
          <% end %>
        </p>
      <% end %>
    </div> <!-- col-md-4 -->

  </div> <!-- row -->
</div> <!-- container -->

<!-- blog -->