config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :products do
  	member do 
	  	get 'back'
	  	get 'report'
      get 'like'
	  end
    collection do
      get 'favorite'
      get 'popular'
      get 'recommended'
    end
  end 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks",registrations: 'registrations' }
  root 'home#index'

  get 'my_projects' =>'products#my_products'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/back_product.rb
class BackProduct < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :back_products,:dependent => :destroy
	has_many :report_products,:dependent => :destroy

	acts_as_taggable

	ratyrate_rateable "speed", "engine", "price"
	acts_as_likeable

	has_attached_file :image, styles: { small: "64x64>", large: "250x250>" }
	has_attached_file :video
	
	validates_attachment :image, presence: true, :content_type => { :content_type => /\Aimage/ }, :size => { :in => 0..5.megabytes }
  validates_attachment :video, presence: true, :content_type => { :content_type => /\Avideo/ }, :size => { :in => 0..25.megabytes }

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true


end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/report_product.rb
class ReportProduct < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  
  ratyrate_rater
  acts_as_liker
  
  has_many :products
  has_many :back_products
  has_many :report_products

  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, presence: true, :content_type => { :content_type => /\Aimage/ }, :size => { :in => 0..5.megabytes }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.uid+"@facebook.com"
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.skip_confirmation! 
      user.save!
    end
  end

  def self.from_google_omnioauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      user.skip_confirmation! 
      user.save!
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@popular_products = Product.all.where('backers_total >?',0).order(:backers_total).limit(3)
  	@recommended_products = Product.all.limit(3)
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger" id="error_explanation">
      <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
          <li style="list-style-type:none;">
            <b>#{messages}</b>
          </li>
        </ul>
    </div>
    <!-- <div id="error_explanation">
      <ul>#{messages}</ul>
    </div> -->
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyStartup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!-- Header -->
		<nav class="navbar navbar-default customnav" id="ForTopHeader">
		  <div class="container">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		     <!-- <a class="navbar-brand regularfont" href="index.html"><span class="darkblue">KICK</span><span class="green">STARTER</span></a>-->
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Explore <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		          	<li><%= link_to "Home", root_path %></li>
		            <li><%= link_to "All Projects", products_path %></li>
		            <li><%= link_to "My Projects", my_projects_path %></li>
		            <li><%= link_to "Favorite Projects", favorite_products_path %></li>
		            <li><%= link_to "Popular Projects", popular_products_path %></li>	
		          </ul>
		        </li>
		        <li class=""><%= link_to "Start a project", new_product_path %></li>
		        <li><%= link_to "For you", recommended_products_path %></li>
		        <li class="marginLeft150">
		        	<%= link_to root_path, :class=>"regularfont font20" do %>
		        		<span class="darkblue">KICK</span><span class="green">STARTER</span>
		        	<% end %>
		        </li>

		      </ul>

		      
		      <ul class="nav navbar-nav navbar-right forMedia768">
		      
		      
		      <form class="navbar-form navbar-left">
		        <!--<div class="form-group">
		          <input type="text" class="form-control" placeholder="Search">
		        </div>
		        <button type="submit" class="btn btn-default">Submit</button>-->
		   

		        <div class="input-group">
			      <input type="text" class="form-control" placeholder="Search for...">
			      <span class="input-group-btn">
			        <button class="btn btn-default" type="button">Go!</button>
			      </span>
			    </div><!-- /input-group -->
		      </form>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= fa_icon "user" %></i> <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		          	<% if user_signed_in? %>
				      	  <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
				      	  <li><%= link_to('Edit Profile', edit_user_registration_path) %></li>
				        <% else %>
				          <li>
				          	<%= link_to "Login", new_user_session_path, :class => 'sign'  %>
				          </li>
				          <li>
				           	<%= link_to "Sign up", new_user_registration_path,:class=>"sign" %>
				          </li>
				        <% end %>
		            
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

		<!-- Header -->

  	<!-- <div class="row" style="background-color:#67AB9F;">
	    <div class="col-md-4">
	      <div class="navbar-header">
	        <p>Company StartUp</p>
	      </div>
	    </div>
	    <div class="col-md-8 navbar-header">
	      <ul>
	        <% if user_signed_in? %>
	      	  <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
	      	  <li><%= link_to('Edit Profile', edit_user_registration_path) %></li>
	        <% else %>
	          <li>
	          	<%= link_to "Login", new_user_session_path, :class => 'sign'  %>
	          </li>
	          <li>
	           	<%= link_to "Sign up", new_user_registration_path,:class=>"sign" %>
	          </li>
	        <% end %>
	      	
	      </ul>
	    </div>
	  </div> -->
	  <!-- NAV SECTION END -->
		<div class="row" style="margin: 0 5px;">
		  <% flash.each do |key, value| %>
		    <% if key == "alert" %>
		      <div class="alert alert-danger">
		        <a href="#" data-dismiss="alert" class="close">×</a>
		          <ul>
		            <li style="list-style-type:none;">
		              <b><%= value %></b>
		            </li>
		          </ul>
		      </div>
		    <% else %>
		      <div class="alert alert-info">
		        <a href="#" data-dismiss="alert" class="close">×</a>
		          <ul>
		            <li style="list-style-type:none;">
		              <b><%= value %></b>
		            </li>
		          </ul>
		      </div>
		    <% end %>
		  <% end %>
		</div>
    <%= yield %>

    <!-- footer -->

		<div class="footerContent">
			<div class="container">
				
			<div class="row">
				<div class="col-sm-3 col-md-3">
					<ul class="footerList">
						<h4>Crowd Exchange</h4>
						<li>über Crowd Exchange</li>
						<li>Blog</li>
						<li>Team</li>
						<li>Jobs</li>
						<li>Partners</li>
						<li>Kontakt</li>
					</ul>
				</div>
				<div class="col-sm-3 col-md-3">
					<ul class="footerList">
						<h4>Hilfe</h4>
						<li>FAQ</li>
						<li>Gebühren</li>
						<li>Handbuch</li>
						<li>AGB</li>
					</ul>
				</div>
				<div class="col-sm-3 col-md-3">
					<ul class="footerList">
						<h4>Infos</h4>
						<li>Statistik</li>
					</ul>
				</div>
				<div class="col-sm-3 col-md-3">
					<ul class="footerList SocialIcon">
						<h4>Social</h4>
						<li><span><%= fa_icon "facebook" %></span>&nbsp;Facebook</li>
						<li><span><%= fa_icon "twitter" %></span>Twitter</li>
						<li><span><%= fa_icon "instagram" %></span>&nbsp;Instagram</li>

				</div>
			
			</div>	<!-- row -->

			</div>	 <!-- container -->
		</div>

		<div class="footer">
			 <div class="container">						 
			 	<p>
			 		<a href="">Help</a>
			 		<span class="pull-right">&copy; 2017 Kickstarter, PBC
			 			&nbsp;&nbsp;
			 		<a href="#ForTopHeader" class="black top-Icon-new"> <span class="fa fa-arrow-up"></span></a>
			 		</span> 
			 	</p>	
			 </div>
		</div>
		<!-- footer -->

  </body>
</html>